### ISSUE TITLE
Change docker installation to follow our version_policy matrix

### ISSUE THREAD

**Issue by MrMarvin** [dcos-terraform/terraform-aws-tested-oses#2]
According to our [official documentation](https://docs.mesosphere.com/version-policy/#dcos-platform-version-compatibility-matrix) we do only support Docker CE 17.05+.

https://github.com/dcos-terraform/terraform-aws-tested-oses/blob/2afb4e5e835990200e1c4d7d4ad8c3db31ccfe54/platform/cloud/aws/centos_7.4/setup.sh#L20

**Comment by jrx** [comment]
@geekbass @fatz 

Besides having the accurate Docker version (currently it is just the latest one) I also noticed that the prereq script is installing with out the `yes` flag for docker-ce:

```
sudo yum install docker-ce
```

https://github.com/dcos-terraform/terraform-aws-tested-oses/blob/master/platform/cloud/aws/centos_7.4/setup.sh#L9

So this will stale the the setup process.
